/**
 * content.js — YouTube AI Assistant v5.2
 *
 * FIXES vs v5.1:
 *  ✅ Search is fully context-aware — knows your video topic, pre-fills suggestions
 *  ✅ AI synthesis prompt includes video context + what user was watching
 *  ✅ Browser/Wikipedia renders clean text — no HTML tags visible
 *  ✅ Wikipedia article body is formatted as readable paragraphs
 *  ✅ Search passes videoTitle+description to background for smarter results
 */
(function () {
  "use strict";

  const SYSTEM_PROMPT = `You are an expert AI assistant embedded inside YouTube — senior software engineer, technical educator, and intelligent tutor combined.

## ABSOLUTE RULES
1. NEVER say "I cannot" or "I don't know". Fill gaps with expert knowledge and clearly note it.
2. ALWAYS answer completely. Partial answers are failures.
3. ALWAYS use proper markdown: **bold**, \`code\`, fenced code blocks, headers, bullet lists.

## CODE ANSWERS
- Output FULL, COMPLETE, RUNNABLE code. No truncating or "..." placeholders.
- Use fenced code blocks with correct language tags.
- Include ALL imports, class definitions, helper functions, error handling.
- Explain code section-by-section after showing it.

## EXPLANATIONS
- Use concrete examples always. For algorithms: show complexity. For concepts: use analogies.

## MULTILINGUAL
- Understand Hindi, Hinglish, English. Match response language to user's question.

## RESPONSE LENGTH
Summaries: 250-400 words. Explanations: 150-300 words. Code: full + 100-200 word explanation.`;

  const PANEL_ID  = "ytai-panel";
  const TOGGLE_ID = "ytai-toggle";
  const MAX_HIST  = 12;
  const LONG_THRESHOLD = 600;
  const DEFAULT_W = 420, DEFAULT_H = 680;
  const MIN_W = 340, MAX_W = 900, MIN_H = 400, MAX_H = 950;

  let state = {
    videoId:"", videoTitle:"", videoDescription:"", channelName:"",
    transcript:null, transcriptErr:null, transcriptLang:"en",
    isLoading:false, chatHistory:[], panelOpen:false,
    indexBuilt:false, msgCount:0, hasApiKey:false,
    responseLang:"en",
    activeTab:"chat",
    provider:"auto",
    activeProvider:"Auto",
    panelW: lp("ytai_w", DEFAULT_W),
    panelH: lp("ytai_h", DEFAULT_H),
  };

  function lp(k,d){ try{const v=parseInt(localStorage.getItem(k));return isNaN(v)?d:v;}catch{return d;} }
  function sp(k,v){ try{localStorage.setItem(k,v);}catch{} }

  // ── Init ──────────────────────────────────────────────────────────────────
  init();
  function init(){ injectUI(); checkApiKey(); loadVideo(); watchNav(); }

  // ── Navigation ────────────────────────────────────────────────────────────
  function watchNav() {
    document.addEventListener("yt-navigate-finish",()=>{
      if(location.pathname==="/watch"){
        const id=new URLSearchParams(location.search).get("v");
        if(id&&id!==state.videoId){ resetVideo(); loadVideo(); }
      }
    });
    let last=location.href;
    new MutationObserver(()=>{
      if(location.href!==last){ last=location.href;
        if(location.pathname==="/watch"){
          const id=new URLSearchParams(location.search).get("v");
          if(id&&id!==state.videoId){ resetVideo(); loadVideo(); }
        }
      }
    }).observe(document.body,{childList:true,subtree:true});
  }

  function resetVideo(){
    const{responseLang,hasApiKey,panelOpen,panelW,panelH,activeTab,provider,activeProvider}=state;
    state={videoId:"",videoTitle:"",videoDescription:"",channelName:"",
      transcript:null,transcriptErr:null,transcriptLang:"en",
      isLoading:false,chatHistory:[],panelOpen,indexBuilt:false,msgCount:0,hasApiKey,
      responseLang,activeTab,panelW,panelH,provider,activeProvider};
    clearChat(); setStatus("loading","Loading new video…");
  }

  async function loadVideo(){
    const vid=new URLSearchParams(location.search).get("v");
    if(!vid) return;
    state.videoId=vid;
    setStatus("loading","Analyzing video…");
    await sleep(1800);
    state.videoTitle       = TranscriptExtractor.getVideoTitle();
    state.videoDescription = TranscriptExtractor.getVideoDescription?.() || "";
    state.channelName      = TranscriptExtractor.getChannelName?.()      || "";
    updateVideoInfo();
    // Update search tab suggestions to match current video
    updateSearchSuggestions();
    setStatus("loading","Extracting transcript…");
    const result = await TranscriptExtractor.extract();
    if(result.error){
      state.transcriptErr=result.error;
      setStatus("warn", result.error+" — AI knowledge fallback active."); return;
    }
    state.transcript=result.segments; state.transcriptLang=result.langCode||"en";
    const n=RAGEngine.buildIndex(result.segments); state.indexBuilt=true;
    const lang=result.language||result.langCode||"en";
    const hi=state.transcriptLang==="hi"||lang.toLowerCase().includes("hindi");
    setStatus("ready",`Ready · ${n} chunks · ${hi?"🇮🇳 Hindi":lang}${result.isAutoGenerated?" · Auto":""}`);
  }

  // ── API Key ───────────────────────────────────────────────────────────────
  function checkApiKey(){
    chrome.runtime.sendMessage({type:"GET_API_KEY"},(res)=>{
      if(chrome.runtime.lastError) return;
      state.hasApiKey=!!(res&&res.key); updateKeyStatus();
    });
  }
  function updateKeyStatus(){
    const el=qs("#ytai-key-status"); if(!el) return;
    el.className=state.hasApiKey?"ytai-key-status connected":"ytai-key-status dimmed";
    el.textContent=state.hasApiKey?"✓ Gemini key active":"Using built-in DeepSeek + Groq";
  }

  // ── UI Build ──────────────────────────────────────────────────────────────
  function injectUI(){
    if(document.getElementById(PANEL_ID)) return;
    const btn=document.createElement("button");
    btn.id=TOGGLE_ID;
    btn.innerHTML=`<div class="ytai-pulse-ring"></div>${svgSparkle(22)}`;
    btn.title="YouTube AI Assistant";
    btn.addEventListener("click",()=>togglePanel());
    document.body.appendChild(btn);
    const panel=document.createElement("div");
    panel.id=PANEL_ID;
    panel.style.width=state.panelW+"px"; panel.style.height=state.panelH+"px";
    panel.innerHTML=buildHTML();
    document.body.appendChild(panel);
    wireEvents(); initResize(panel); initDrag(panel); // Drag Support
  }

  function buildHTML(){
    return `
      <div class="ytai-resize-n"  data-dir="n"></div><div class="ytai-resize-e"  data-dir="e"></div>
      <div class="ytai-resize-s"  data-dir="s"></div><div class="ytai-resize-w"  data-dir="w"></div>
      <div class="ytai-resize-nw" data-dir="nw"></div><div class="ytai-resize-ne" data-dir="ne"></div>
      <div class="ytai-resize-se" data-dir="se"></div><div class="ytai-resize-sw" data-dir="sw"></div>

      <div class="ytai-header">
        <div class="ytai-header-top">
          <div class="ytai-logo">${svgSparkle(15)}</div>
          <div class="ytai-brand">
            <div class="ytai-brand-name">YouTube AI</div>
            <div class="ytai-brand-sub" id="ytai-provider-sub">Auto-fallback</div>
          </div>
          <div class="ytai-provider-picker" id="ytai-provider-picker">
            <button class="ytai-prov-btn active" data-prov="auto"     title="Auto-fallback">Auto</button>
            <button class="ytai-prov-btn"         data-prov="gemini"  title="Gemini">G</button>
            <button class="ytai-prov-btn deepseek" data-prov="deepseek" title="DeepSeek">DS</button>
            <button class="ytai-prov-btn groq"    data-prov="groq"    title="Groq">GQ</button>
          </div>
          <div class="ytai-header-actions">
            <button class="ytai-icon-btn" id="ytai-clear-btn" title="Clear chat">${svgTrash()}</button>
            <button class="ytai-icon-btn close" id="ytai-close-btn" title="Close">${svgX()}</button>
          </div>
        </div>
      </div>

      <div class="ytai-video-strip">${svgFilm()}<span class="ytai-video-title" id="ytai-video-title">Loading video…</span></div>
      <div class="ytai-status-bar"><div class="ytai-dot loading" id="ytai-dot"></div><span id="ytai-status-text">Initializing…</span></div>

      <div class="ytai-tabs">
        <button class="ytai-tab active" data-tab="chat">${svgSparkle(11)} Chat</button>
        <button class="ytai-tab"        data-tab="search">🔍 Search</button>
        <button class="ytai-tab"        data-tab="browser">📖 Browser</button>
        <button class="ytai-tab"        data-tab="settings">⚙️</button>
      </div>

      <!-- ─── CHAT TAB ─── -->
      <div class="ytai-tabpane active" id="ytai-pane-chat">
        <div class="ytai-actions">
          <button class="ytai-action-pill" data-action="summarize">📋 Summarize</button>
          <button class="ytai-action-pill" data-action="keypoints">🎯 Key Points</button>
          <button class="ytai-action-pill" data-action="moments">🕐 Moments</button>
          <button class="ytai-action-pill" data-action="code">💻 Get Code</button>
          <button class="ytai-action-pill" data-action="explain">💡 Explain</button>
        </div>
        <div class="ytai-lang-toggle">
          <span class="ytai-lang-label">Reply in</span>
          <div class="ytai-lang-pills">
            <button class="ytai-lang-pill active" data-lang="en">English</button>
            <button class="ytai-lang-pill" data-lang="hi">हिंदी</button>
            <button class="ytai-lang-pill" data-lang="auto">Auto</button>
          </div>
        </div>
        <div class="ytai-chat" id="ytai-chat">
          <div class="ytai-empty" id="ytai-empty">
            <div class="ytai-empty-icon">${svgSparkle(38)}</div>
            <p class="ytai-empty-title">Ask anything about this video</p>
            <p class="ytai-empty-hint">Transcripts · Code · Concepts · Timestamps</p>
          </div>
        </div>
        <div class="ytai-input-area">
          <div class="ytai-input-wrap">
            <textarea id="ytai-input" class="ytai-textarea" placeholder="Ask about this video…" rows="1" maxlength="1000"></textarea>
          </div>
          <button id="ytai-send" class="ytai-send-btn">${svgSend()}</button>
        </div>
      </div>

      <!-- ─── SEARCH TAB ─── -->
      <div class="ytai-tabpane" id="ytai-pane-search">
        <div class="ytai-search-bar-row">
          <input id="ytai-search-input" class="ytai-search-input" type="text" placeholder="Search the web…" />
          <button id="ytai-search-go" class="ytai-search-go-btn">Go</button>
        </div>
        <!-- Context chips — populated dynamically after video loads -->
        <div class="ytai-search-ctx" id="ytai-search-ctx" style="display:none">
          <span class="ytai-ctx-label">🎬 Related:</span>
          <div class="ytai-ctx-chips" id="ytai-ctx-chips"></div>
        </div>
        <div class="ytai-search-results-area" id="ytai-search-results">
          <div class="ytai-empty">
            <div class="ytai-empty-icon">🔍</div>
            <p class="ytai-empty-title">Native YouTube Search</p>
            <p class="ytai-empty-hint">Results fetch highly relevant YouTube videos.<br>100% video recommendations.</p>
          </div>
        </div>
      </div>

      <!-- ─── BROWSER TAB ─── -->
      <div class="ytai-tabpane" id="ytai-pane-browser">
        <div class="ytai-browser-toolbar">
          <button class="ytai-nav-btn" id="ytai-wiki-home" title="Home">🏠</button>
          <input id="ytai-wiki-search" class="ytai-browser-url-input" type="text" placeholder="Search Wikipedia…" />
          <button class="ytai-nav-btn ytai-nav-go" id="ytai-wiki-go">Go</button>
        </div>
        <div class="ytai-wiki-content" id="ytai-wiki-content">
          <div class="ytai-wiki-home">
            <div class="ytai-wiki-logo">📖</div>
            <h2>Wikipedia Browser</h2>
            <p>Search any topic to read clean articles.<br>Uses Wikipedia's API — no iframe blocks.</p>
            <div class="ytai-wiki-suggestions" id="ytai-wiki-sug-home">
              <button class="ytai-wiki-sug" data-q="Artificial Intelligence">🤖 AI</button>
              <button class="ytai-wiki-sug" data-q="Machine Learning">🧠 ML</button>
              <button class="ytai-wiki-sug" data-q="Python programming">🐍 Python</button>
              <button class="ytai-wiki-sug" data-q="JavaScript">📜 JavaScript</button>
              <button class="ytai-wiki-sug" data-q="Deep Learning">🔬 Deep Learning</button>
              <button class="ytai-wiki-sug" data-q="Neural Network">🕸️ Neural Nets</button>
            </div>
          </div>
        </div>
      </div>

      <!-- ─── SETTINGS TAB ─── -->
      <div class="ytai-tabpane" id="ytai-pane-settings">
        <div class="ytai-settings-scroll">
          <div class="ytai-settings-section">
            <div class="ytai-settings-title">🤖 AI Provider Chain</div>
            <div class="ytai-provider-chain">
              <div class="ytai-prov-row" id="sett-gemini">
                <div class="ytai-prov-dot"></div>
                <div class="ytai-prov-info"><strong>1. Gemini 2.5 Flash</strong><span>Add your key for best limits</span></div>
                <span class="ytai-prov-tag key" id="sett-gemini-tag">No key</span>
              </div>
              <div class="ytai-chain-arrow">↓ auto-fallback</div>
              <div class="ytai-prov-row ds">
                <div class="ytai-prov-dot"></div>
                <div class="ytai-prov-info"><strong>2. DeepSeek Chat</strong><span>Built-in key · Free</span></div>
                <span class="ytai-prov-tag free">Built-in</span>
              </div>
              <div class="ytai-chain-arrow">↓ auto-fallback</div>
              <div class="ytai-prov-row gq">
                <div class="ytai-prov-dot"></div>
                <div class="ytai-prov-info"><strong>3. Groq · Llama 3.3 70B</strong><span>Built-in key · Free</span></div>
                <span class="ytai-prov-tag free">Built-in</span>
              </div>
            </div>
          </div>
          <div class="ytai-settings-section">
            <div class="ytai-settings-title">🔑 Your API Keys <span class="ytai-opt-tag">optional</span></div>
            <div class="ytai-setup-row" style="margin-bottom:6px">
              <input id="ytai-key-input-gemini" class="ytai-key-input" type="password" placeholder="Gemini Key (AIzaSy…)" autocomplete="off"/>
            </div>
            <div class="ytai-setup-row" style="margin-bottom:6px">
              <input id="ytai-key-input-deepseek" class="ytai-key-input" type="password" placeholder="DeepSeek Key (sk-…)" autocomplete="off"/>
            </div>
            <div class="ytai-setup-row" style="margin-bottom:6px">
              <input id="ytai-key-input-groq" class="ytai-key-input" type="password" placeholder="Groq Key (gsk_…)" autocomplete="off"/>
            </div>
            <div class="ytai-setup-row">
              <button id="ytai-key-save" class="ytai-key-save" style="width:100%">Save Keys</button>
            </div>
            <div class="ytai-key-status dimmed" id="ytai-key-status">Using built-in DeepSeek + Groq</div>
            <div class="ytai-setup-hint"><a href="https://aistudio.google.com/apikey" target="_blank">Get free key →</a> Adds higher personal limits.</div>
          </div>
          <div class="ytai-settings-section">
            <div class="ytai-settings-title">📐 Panel Size Presets</div>
            <div class="ytai-size-btns">
              <button class="ytai-size-btn" data-w="340" data-h="500">Compact</button>
              <button class="ytai-size-btn" data-w="420" data-h="680">Default</button>
              <button class="ytai-size-btn" data-w="560" data-h="800">Large</button>
              <button class="ytai-size-btn" data-w="720" data-h="900">XL</button>
            </div>
          </div>
        </div>
      </div>

      <div class="ytai-footer" id="ytai-footer">YouTube AI Assistant v5.2</div>
    `;
  }

  // ── Event Wiring ──────────────────────────────────────────────────────────
  function wireEvents(){
    qs("#ytai-close-btn").addEventListener("click",()=>togglePanel(false));
    qs("#ytai-clear-btn").addEventListener("click",()=>{ clearChat(); state.chatHistory=[]; state.msgCount=0; });

    document.querySelectorAll(".ytai-tab").forEach(t=>t.addEventListener("click",()=>switchTab(t.dataset.tab)));

    document.querySelectorAll(".ytai-prov-btn").forEach(btn=>{
      btn.addEventListener("click",()=>{
        document.querySelectorAll(".ytai-prov-btn").forEach(b=>b.classList.remove("active"));
        btn.classList.add("active"); state.provider=btn.dataset.prov; updateProviderSub();
      });
    });

    document.querySelectorAll(".ytai-lang-pill").forEach(p=>{
      p.addEventListener("click",()=>{
        document.querySelectorAll(".ytai-lang-pill").forEach(x=>x.classList.remove("active"));
        p.classList.add("active"); state.responseLang=p.dataset.lang;
      });
    });

    document.querySelectorAll(".ytai-action-pill[data-action]").forEach(p=>{
      p.addEventListener("click",()=>handleQuickAction(p.dataset.action));
    });

    const inp=qs("#ytai-input"), send=qs("#ytai-send");
    send.addEventListener("click",handleChat);
    inp.addEventListener("keydown",e=>{ if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();handleChat();} });
    inp.addEventListener("input",()=>{ inp.style.height="auto"; inp.style.height=Math.min(inp.scrollHeight,120)+"px"; });

    const si=qs("#ytai-search-input"), sg=qs("#ytai-search-go");
    sg.addEventListener("click",runSearch);
    si.addEventListener("keydown",e=>{ if(e.key==="Enter") runSearch(); });

    const wi=qs("#ytai-wiki-search"), wg=qs("#ytai-wiki-go");
    wg.addEventListener("click",()=>loadWikiArticle(wi.value.trim()));
    wi.addEventListener("keydown",e=>{ if(e.key==="Enter") loadWikiArticle(wi.value.trim()); });
    qs("#ytai-wiki-home").addEventListener("click",showWikiHome);
    document.querySelectorAll(".ytai-wiki-sug").forEach(btn=>{
      btn.addEventListener("click",()=>loadWikiArticle(btn.dataset.q));
    });

    qs("#ytai-key-save").addEventListener("click",saveApiKey);
    const kiGem = qs("#ytai-key-input-gemini"), kiDs = qs("#ytai-key-input-deepseek"), kiGq = qs("#ytai-key-input-groq");
    [kiGem, kiDs, kiGq].forEach(el => {
      if(el) el.addEventListener("keydown",e=>{ if(e.key==="Enter") saveApiKey(); });
    });

    document.querySelectorAll(".ytai-size-btn").forEach(b=>{
      b.addEventListener("click",()=>{
        const p=document.getElementById(PANEL_ID), w=parseInt(b.dataset.w), h=parseInt(b.dataset.h);
        p.style.width=w+"px"; p.style.height=h+"px"; state.panelW=w; state.panelH=h; sp("ytai_w",w); sp("ytai_h",h);
      });
    });
  }

  function updateProviderSub(){
    const sub=qs("#ytai-provider-sub");
    const labels={auto:"Auto-fallback",gemini:"Gemini 2.5",deepseek:"DeepSeek",groq:"Groq Llama 3.3"};
    if(sub) sub.textContent=labels[state.provider]||"Auto-fallback";
  }

  function switchTab(tab){
    state.activeTab=tab;
    document.querySelectorAll(".ytai-tab").forEach(t=>t.classList.toggle("active",t.dataset.tab===tab));
    document.querySelectorAll(".ytai-tabpane").forEach(p=>p.classList.toggle("active",p.id===`ytai-pane-${tab}`));
    const footer=qs("#ytai-footer");
    if(footer) footer.textContent=tab==="browser"?"📖 Wikipedia Browser · No iframe issues":"YouTube AI Assistant v5.2";
  }

  // ── Context-Aware Search ──────────────────────────────────────────────────

  /** Build topic chips from the video title */
  function updateSearchSuggestions(){
    const ctx=qs("#ytai-search-ctx"), chips=qs("#ytai-ctx-chips");
    if(!ctx||!chips||!state.videoTitle) return;

    // Extract key terms from video title (strip noise words, keep meaningful ones)
    const noiseWords = new Set(["the","a","an","and","or","in","on","at","for","to","of","with","by","from","is","how","what","why","when","this","that","all","full","course","tutorial","complete","guide","learn","beginner","advanced","#generativeai","#artificialintelligence"]);
    const terms = state.videoTitle
      .replace(/#\w+/g,"")           // strip hashtags
      .replace(/[^\w\s]/g," ")       // strip punctuation
      .split(/\s+/)
      .filter(w => w.length > 3 && !noiseWords.has(w.toLowerCase()))
      .slice(0, 6);

    if(!terms.length) return;

    chips.innerHTML = "";
    // Always add "overview" of the topic
    const titleShort = state.videoTitle.slice(0,40);
    const allChips = [titleShort, ...terms];

    allChips.slice(0,5).forEach(term => {
      const btn = document.createElement("button");
      btn.className = "ytai-ctx-chip";
      btn.textContent = term;
      btn.addEventListener("click", () => {
        qs("#ytai-search-input").value = term;
        runSearch();
      });
      chips.appendChild(btn);
    });
    ctx.style.display = "flex";
  }

  async function runSearch(){
    const q=qs("#ytai-search-input")?.value.trim();
    if(!q) return;
    const area=qs("#ytai-search-results");
    area.innerHTML=`<div class="ytai-search-loading">🔍 Searching with video context…</div>`;
    try {
      const res=await new Promise((ok,fail)=>{
        chrome.runtime.sendMessage({
          type:"SEARCH_REQUEST",
          payload:{
            query: q,
            videoTitle:       state.videoTitle       || "",
            videoDescription: state.videoDescription || "",
            channelName:      state.channelName      || "",
          },
        }, r=>{
          if(chrome.runtime.lastError) fail(new Error(chrome.runtime.lastError.message));
          else if(!r?.success)         fail(new Error(r?.error||"Search failed"));
          else ok(r.data);
        });
      });
      renderSearchResults(area, res, q);
    } catch(e){
      area.innerHTML=`<div class="ytai-empty"><p class="ytai-empty-title">Search failed</p><p class="ytai-empty-hint">${escHtml(e.message)}</p></div>`;
    }
  }

  function renderSearchResults(container, data, query){
    const{provider,results,quickAnswer,definition,videoTitle}=data;
    let html=`
      <div class="ytai-search-header">
        <span class="ytai-search-for">Results for <em>"${escHtml(query)}"</em></span>
        <span class="ytai-search-prov">${provider}</span>
      </div>`;
    if(quickAnswer) html+=`<div class="ytai-search-quick"><strong>⚡</strong> ${escHtml(quickAnswer)}</div>`;
    if(definition)  html+=`<div class="ytai-search-quick"><strong>📖</strong> ${escHtml(definition)}</div>`;
    if(!results?.length){
      html+=`<div class="ytai-search-empty">No results found. Try different keywords.</div>`;
    } else {
      html+=`<div class="ytai-search-cards" style="background:#0a0a0f;">`;
      results.forEach(r=>{
        html+=`
          <a class="ytai-search-card ytai-yt-card" href="${escAttr(r.url)}" target="_blank" rel="noopener">
            ${r.thumbnail ? `<div class="ytai-yt-thumb"><img src="${escAttr(r.thumbnail)}" alt="Thumbnail"></div>` : ''}
            <div class="ytai-yt-details">
              <span class="ytai-search-card-title">${escHtml(r.title)}</span>
              <div class="ytai-search-card-snippet">${escHtml(r.snippet)}</div>
              ${r.badge && r.badge !== 'YouTube' ? `<span class="ytai-search-badge ytai-badge-youtube" style="margin-top:6px;width:fit-content">${escHtml(r.badge)}</span>` : ""}
            </div>
          </a>`;
      });
      html+=`</div>`;
    }
    html+=`<button class="ytai-search-ask-ai" id="ytai-ask-ai-btn">✨ Ask AI to explain these videos in context</button>`;
    container.innerHTML=html;

    qs("#ytai-ask-ai-btn")?.addEventListener("click", async(e)=>{
      const btn=e.currentTarget;
      btn.disabled=true; btn.textContent="Thinking…";
      switchTab("chat"); removeEmpty();
      addUserMsg(`Search summary: "${query}"`);
      const tid=showTyping();
      const resText=(results||[]).map(r=>`${r.title}: ${r.snippet||""}`).join("\n\n");

      // ── Context-aware AI synthesis prompt ──────────────────────────────
      // Tell the AI: what video is being watched + what the user searched + the results
      const videoCtx = state.videoTitle
        ? `The user is currently watching a YouTube video titled: "${state.videoTitle}"${state.channelName ? ` by "${state.channelName}"` : ""}.`
        : "";
      const transcriptCtx = state.indexBuilt
        ? " They have transcript context available from the video."
        : "";

      const synthesisPrompt = `${videoCtx}${transcriptCtx}

The user searched for: "${query}"

Here are the web search results:
${resText}

INSTRUCTIONS:
1. Synthesize these results into a clear, accurate answer.
2. ${state.videoTitle ? `Connect findings to the video topic "${state.videoTitle}" where relevant.` : "Focus on what is most useful."}
3. Highlight the most important points using **bold**.
4. Note any disagreements or gaps between sources.
5. End with 1-2 practical takeaways.`;

      try {
        const r=await callAI(
          "You are a helpful AI that synthesizes web search results clearly. You are aware of the YouTube video the user is watching and connect search results to their learning context.",
          synthesisPrompt,
          []
        );
        removeTyping(tid); addAiMsg(r.data,r.provider);
      } catch(err){ removeTyping(tid); addErrMsg(err.message); }
    });
  }

  // ── Wikipedia Browser ─────────────────────────────────────────────────────
  async function loadWikiArticle(query){
    if(!query) return;
    const content=qs("#ytai-wiki-content");
    qs("#ytai-wiki-search").value=query;
    content.innerHTML=`<div class="ytai-wiki-loading"><div class="ytai-wiki-spinner"></div><p>Loading "${escHtml(query)}"…</p></div>`;

    try {
      const res=await new Promise((ok,fail)=>{
        chrome.runtime.sendMessage({type:"WIKI_FETCH",query}, r=>{
          if(chrome.runtime.lastError) fail(new Error(chrome.runtime.lastError.message));
          else if(!r?.success) fail(new Error(r?.error||"Failed"));
          else ok(r.data);
        });
      });

      if(!res.found){
        content.innerHTML=`<div class="ytai-wiki-notfound">
          <div class="ytai-empty-icon">🔍</div>
          <p class="ytai-empty-title">No article found for "${escHtml(query)}"</p>
          <p class="ytai-empty-hint">Try a different search term</p></div>`;
        return;
      }

      // ── Render clean text (no HTML tags) ─────────────────────────────
      // The extract is already plain text (background.js uses explaintext=1 + stripHtml)
      const paragraphs = res.extract
        .split(/\n\n+/)
        .filter(p => p.trim().length > 20)
        .map(p => `<p>${escHtml(p.trim())}</p>`)
        .join("");

      const sectionsHtml = res.sections?.length
        ? `<div class="ytai-wiki-sections"><strong>Sections:</strong>
            ${res.sections.map(s=>`<button class="ytai-wiki-sug-sm" data-q="${escAttr(res.title+" "+s)}">${escHtml(s)}</button>`).join("")}
           </div>`
        : "";

      content.innerHTML=`
        <div class="ytai-wiki-article">
          <div class="ytai-wiki-art-header">
            <h1 class="ytai-wiki-art-title">${escHtml(res.title)}</h1>
            <a class="ytai-wiki-open-link" href="${escAttr(res.url)}" target="_blank" rel="noopener">Open in Wikipedia ↗</a>
          </div>
          ${sectionsHtml}
          <div class="ytai-wiki-art-body">${paragraphs || `<p>${escHtml(res.extract)}</p>`}</div>
          <div class="ytai-wiki-art-footer">
            <button class="ytai-wiki-ask-ai" data-title="${escAttr(res.title)}" data-text="${escAttr(res.extract.slice(0,1500))}">
              ✨ Ask AI about this article
            </button>
          </div>
        </div>`;

      // Wire section chips
      content.querySelectorAll(".ytai-wiki-sug-sm").forEach(btn=>{
        btn.addEventListener("click",()=>loadWikiArticle(btn.dataset.q));
      });

      // Wire "Ask AI" button
      content.querySelector(".ytai-wiki-ask-ai")?.addEventListener("click", async(e)=>{
        const btn=e.currentTarget;
        const title=btn.dataset.title, text=btn.dataset.text;
        btn.disabled=true; btn.textContent="Thinking…";
        switchTab("chat"); removeEmpty();
        addUserMsg(`Explain: ${title}`);
        const tid=showTyping();

        const videoCtx = state.videoTitle
          ? `The user is watching a YouTube video titled "${state.videoTitle}". `
          : "";

        try {
          const result=await callAI(
            "You are an expert at explaining Wikipedia articles clearly and connecting them to relevant learning contexts.",
            `${videoCtx}They want to understand this Wikipedia article:\n\nTitle: "${title}"\n\nContent:\n${text}\n\nExplain this clearly with: 1) What it is, 2) Key concepts, 3) Why it matters${state.videoTitle ? `, 4) How it connects to "${state.videoTitle}"` : ""}.`,
            []
          );
          removeTyping(tid); addAiMsg(result.data,result.provider);
        } catch(err){ removeTyping(tid); addErrMsg(err.message); }
      });

    } catch(err){
      content.innerHTML=`<div class="ytai-wiki-notfound"><div class="ytai-empty-icon">⚠️</div>
        <p class="ytai-empty-title">Error loading article</p>
        <p class="ytai-empty-hint">${escHtml(err.message)}</p></div>`;
    }
  }

  function showWikiHome(){
    qs("#ytai-wiki-search").value="";
    const c=qs("#ytai-wiki-content");
    // Build home with video-aware suggestions if we have a title
    const videoSugs = state.videoTitle
      ? state.videoTitle.replace(/#\w+/g,"").split(/\s+/)
          .filter(w=>w.length>3)
          .slice(0,3)
          .map(w=>`<button class="ytai-wiki-sug" data-q="${escAttr(w)}">${escHtml(w)}</button>`)
          .join("")
      : "";
    c.innerHTML=`
      <div class="ytai-wiki-home">
        <div class="ytai-wiki-logo">📖</div>
        <h2>Wikipedia Browser</h2>
        <p>Search any topic. Clean articles via Wikipedia's API.</p>
        ${videoSugs ? `<p style="font-size:11px;color:var(--ytai-text-muted);margin:8px 0 4px">Video topics:</p><div class="ytai-wiki-suggestions">${videoSugs}</div>` : ""}
        <div class="ytai-wiki-suggestions" id="ytai-wiki-sug-home">
          <button class="ytai-wiki-sug" data-q="Artificial Intelligence">🤖 AI</button>
          <button class="ytai-wiki-sug" data-q="Machine Learning">🧠 ML</button>
          <button class="ytai-wiki-sug" data-q="Python programming">🐍 Python</button>
          <button class="ytai-wiki-sug" data-q="Deep Learning">🔬 Deep Learning</button>
        </div>
      </div>`;
    c.querySelectorAll(".ytai-wiki-sug").forEach(btn=>{
      btn.addEventListener("click",()=>loadWikiArticle(btn.dataset.q));
    });
  }

  // ── Settings ──────────────────────────────────────────────────────────────
  function saveApiKey(){
    const gemini=qs("#ytai-key-input-gemini")?.value.trim()||"";
    const deepseek=qs("#ytai-key-input-deepseek")?.value.trim()||"";
    const groq=qs("#ytai-key-input-groq")?.value.trim()||"";
    if(!gemini && !deepseek && !groq) return;

    chrome.runtime.sendMessage({type:"SAVE_API_KEY",gemini,deepseek,groq},(res)=>{
      if(res?.success){
        state.hasApiKey=!!gemini; 
        [qs("#ytai-key-input-gemini"), qs("#ytai-key-input-deepseek"), qs("#ytai-key-input-groq")].forEach(inp=>inp&&(inp.value="")); 
        updateKeyStatus();
        if(gemini) {
          const tag=qs("#sett-gemini-tag");
          if(tag){tag.textContent="Active";tag.className="ytai-prov-tag free";}
        }
        addSysMsg("✅ API keys saved! The requested providers will be prioritized.");
      }
    });
  }

  // ── Quick Actions ─────────────────────────────────────────────────────────
  function handleQuickAction(action){
    const map={
      summarize:"Give me a comprehensive summary of this video. Include: 1) Brief overview 2) Key points 3) Important takeaways 4) Who would benefit",
      keypoints:"What are the key takeaways from this video? Give a numbered list with brief explanations.",
      moments:  "Break this video into main topics/sections with approximate timestamps. Format: [timestamp] Topic — description.",
      code:     "Extract all code shown in this video. For each: complete runnable code + explanation.",
      explain:  "Explain the main topic simply: 1) What is taught 2) Why it matters 3) Key concepts 4) Practical applications.",
    };
    if(map[action]){ if(state.activeTab!=="chat") switchTab("chat"); qs("#ytai-input").value=map[action]; handleChat(); }
  }

  // ── AI Chat ───────────────────────────────────────────────────────────────
  async function handleChat(){
    const inp=qs("#ytai-input"), send=qs("#ytai-send");
    if(!inp) return;
    const q=inp.value.trim();
    if(!q||state.isLoading) return;
    removeEmpty(); addUserMsg(q);
    inp.value=""; inp.style.height="auto";
    state.isLoading=true; send.disabled=true; send.classList.add("sending");
    const tid=showTyping();
    try {
      const prompt=buildPrompt(q);
      let langInstr="";
      if(state.responseLang==="hi")   langInstr="\n\nIMPORTANT: Respond entirely in Hindi (हिंदी).";
      if(state.responseLang==="auto") langInstr="\n\nIMPORTANT: Detect user language from their question and respond in it.";
      const result=await callAI(SYSTEM_PROMPT+langInstr, prompt, state.chatHistory.slice(-MAX_HIST));
      removeTyping(tid); addAiMsg(result.data,result.provider);
      if(result.provider&&result.provider!=="Cache"){ state.activeProvider=result.provider; updateProviderSub(); }
      state.chatHistory.push({role:"user",content:q});
      state.chatHistory.push({role:"assistant",content:result.data});
      state.msgCount++;
    } catch(err){ removeTyping(tid); handleError(err); }
    finally{ state.isLoading=false; send.disabled=false; send.classList.remove("sending"); inp.focus(); }
  }

  async function callAI(systemPrompt, userPrompt, history){
    return new Promise((ok,fail)=>{
      chrome.runtime.sendMessage({
        type:"AI_REQUEST", provider:state.provider,
        payload:{systemPrompt,userPrompt,history},
      }, r=>{
        if(chrome.runtime.lastError) fail(new Error(chrome.runtime.lastError.message));
        else if(!r)         fail(new Error("No response. Reload page (F5)."));
        else if(!r.success) fail(new Error(r.error));
        else ok(r);
      });
    });
  }

  function buildPrompt(q){
    const isCode    =/\bcode\b|\bfunction\b|\bclass\b|\bimport\b|\bscript\b|\.py|\.js|implement|algorithm|loop|array/i.test(q);
    const isSummary =/^(summar|overview|main.{0,10}topic|what.{0,10}video)/i.test(q.trim());
    const isBroad   =/key.?point|key.?takeaway|moments|section|break.?down/i.test(q);
    if(!state.indexBuilt)
      return `VIDEO TITLE: "${state.videoTitle}"\nChannel: ${state.channelName}\n\nNOTE: Transcript unavailable. Use expert knowledge.\n\nQUESTION: ${q}`;
    const k=isCode?6:isSummary?5:isBroad?4:4;
    const chunks=isSummary&&RAGEngine.retrieveAll?RAGEngine.retrieveAll(2500):RAGEngine.retrieve(q,k);
    return RAGEngine.buildUserPrompt(state.videoTitle,q,chunks,{isCode,detectedLang:state.transcriptLang,description:state.videoDescription,channel:state.channelName});
  }

  // ── Error Handling ────────────────────────────────────────────────────────
  function handleError(err){
    const m=err.message;
    if(m==="NO_API_KEY")          { switchTab("settings"); addErrMsg("No AI key found. DeepSeek + Groq built-in keys are being used automatically."); }
    else if(m==="API_KEY_INVALID"){ state.hasApiKey=false; updateKeyStatus(); addErrMsg("Invalid Gemini key. Falling back to DeepSeek + Groq automatically."); }
    else if(m.includes("unavailable")||m.includes("All AI providers")) addErrMsg("All AI providers busy. Wait 30s and retry.");
    else if(m.includes("quota")||m.includes("429")) addErrMsg("Rate limit hit. The system auto-switches providers. Retry in a few seconds.");
    else addErrMsg("Error: "+m);
  }

  // ── Message Rendering ─────────────────────────────────────────────────────
  function addUserMsg(text){
    const c=qs("#ytai-chat"); if(!c) return;
    const w=document.createElement("div"); w.className="ytai-msg ytai-msg-user";
    w.innerHTML=`<div class="ytai-bubble ytai-bubble-user">${escHtml(text)}</div>`;
    c.appendChild(w); scrollBottom();
  }

  function addAiMsg(text, provider){
    const c=qs("#ytai-chat"); if(!c) return;
    const w=document.createElement("div"); w.className="ytai-msg ytai-msg-assistant";
    const html=mdToHtml(text), isLong=text.length>LONG_THRESHOLD, cid="ytai-c-"+state.msgCount;
    const pTag=provider&&provider!=="Cache"
      ?`<span class="ytai-msg-provider ytai-prov-${provider.toLowerCase().replace(/\s.*/,"")}">${provider}</span>`:"";
    w.innerHTML=`
      <div class="ytai-msg-row">
        <div class="ytai-avatar">${svgSparkle(12)}</div>
        <div class="ytai-bubble ytai-bubble-ai">
          ${pTag}
          <div class="ytai-content ${isLong?"ytai-collapsible":""}" id="${cid}">${html}</div>
          ${isLong?`<button class="ytai-expand-btn" data-target="${cid}">Show full answer ▾</button>`:""}
          <div class="ytai-answer-actions">
            <button class="ytai-answer-btn ytai-copy-answer" data-text="${escAttr(text)}">📋 Copy</button>
          </div>
        </div>
      </div>`;
    c.appendChild(w);
    w.querySelectorAll("pre").forEach(pre=>{
      const hdr=pre.previousElementSibling;
      if(hdr?.classList.contains("ytai-code-header"))
        hdr.querySelector(".ytai-copy-btn")?.addEventListener("click",()=>copyClip(pre.querySelector("code")?.textContent||pre.textContent,hdr.querySelector(".ytai-copy-btn")));
    });
    const expBtn=w.querySelector(".ytai-expand-btn");
    if(expBtn){
      const cnt=w.querySelector(`#${expBtn.dataset.target}`); cnt?.classList.add("collapsed");
      expBtn.addEventListener("click",()=>{
        cnt?.classList.toggle("collapsed");
        expBtn.textContent=cnt?.classList.contains("collapsed")?"Show full answer ▾":"Show less ▴";
      });
    }
    w.querySelector(".ytai-copy-answer")?.addEventListener("click",e=>copyClip(text,e.currentTarget,"📋 Copy","✓ Copied!"));
    scrollBottom();
  }

  function addErrMsg(text){
    const c=qs("#ytai-chat"); if(!c) return;
    const w=document.createElement("div"); w.className="ytai-msg ytai-msg-error";
    w.innerHTML=`<div class="ytai-msg-row"><div class="ytai-avatar">${svgSparkle(12)}</div><div class="ytai-bubble ytai-bubble-error"><span class="ytai-err-label">⚠</span>${escHtml(text)}</div></div>`;
    c.appendChild(w); scrollBottom();
  }

  function addSysMsg(text){
    removeEmpty(); const c=qs("#ytai-chat"); if(!c) return;
    const w=document.createElement("div"); w.className="ytai-msg ytai-msg-assistant";
    w.innerHTML=`<div class="ytai-msg-row"><div class="ytai-avatar">${svgSparkle(12)}</div><div class="ytai-bubble ytai-bubble-ai">${escHtml(text)}</div></div>`;
    c.appendChild(w); scrollBottom();
  }

  function showTyping(){
    const id="ytai-t-"+Date.now(), c=qs("#ytai-chat");
    const d=document.createElement("div"); d.id=id; d.className="ytai-msg ytai-msg-assistant";
    d.innerHTML=`<div class="ytai-msg-row"><div class="ytai-avatar">${svgSparkle(12)}</div><div class="ytai-bubble ytai-bubble-ai ytai-typing"><span></span><span></span><span></span></div></div>`;
    c.appendChild(d); scrollBottom(); return id;
  }

  function removeTyping(id){ document.getElementById(id)?.remove(); }
  function removeEmpty()   { qs("#ytai-empty")?.remove(); }
  function clearChat(){
    const c=qs("#ytai-chat"); if(!c) return;
    c.innerHTML=`<div class="ytai-empty" id="ytai-empty"><div class="ytai-empty-icon">${svgSparkle(38)}</div><p class="ytai-empty-title">Ask anything about this video</p><p class="ytai-empty-hint">Transcripts · Code · Concepts · Timestamps</p></div>`;
  }
  function scrollBottom(){ const c=qs("#ytai-chat"); if(c) requestAnimationFrame(()=>{c.scrollTop=c.scrollHeight;}); }

  // ── Panel ─────────────────────────────────────────────────────────────────
  function togglePanel(force){
    state.panelOpen=typeof force==="boolean"?force:!state.panelOpen;
    document.getElementById(PANEL_ID)?.classList.toggle("open",state.panelOpen);
    document.getElementById(TOGGLE_ID)?.classList.toggle("open",state.panelOpen);
    if(state.panelOpen) qs("#ytai-input")?.focus();
  }

  function setStatus(type,msg){
    const dot=qs("#ytai-dot"), txt=qs("#ytai-status-text");
    if(!dot||!txt) return; dot.className=`ytai-dot ${type}`; txt.textContent=msg;
  }

  function updateVideoInfo(){
    const el=qs("#ytai-video-title"); if(el) el.textContent=state.videoTitle||"Unknown video";
  }

  // ── Resize ────────────────────────────────────────────────────────────────
  function initResize(panel){
    panel.querySelectorAll("[class^='ytai-resize-']").forEach(h=>{
      h.addEventListener("mousedown",e=>{
        e.preventDefault(); e.stopPropagation();
        const dir=h.dataset.dir, sx=e.clientX, sy=e.clientY, sw=panel.offsetWidth, sh=panel.offsetHeight;
        document.body.style.userSelect="none"; panel.style.transition="none";
        const mv=me=>{
          const dx=me.clientX-sx, dy=me.clientY-sy; let nw=sw, nh=sh;
          if(dir.includes("e")) nw=clamp(sw+dx,MIN_W,MAX_W);
          if(dir.includes("w")) nw=clamp(sw-dx,MIN_W,MAX_W);
          if(dir.includes("s")) nh=clamp(sh+dy,MIN_H,MAX_H);
          if(dir.includes("n")) nh=clamp(sh-dy,MIN_H,MAX_H);
          panel.style.width=nw+"px"; panel.style.height=nh+"px"; state.panelW=nw; state.panelH=nh;
        };
        const up=()=>{
          document.removeEventListener("mousemove",mv); document.removeEventListener("mouseup",up);
          document.body.style.userSelect=""; panel.style.transition=""; sp("ytai_w",state.panelW); sp("ytai_h",state.panelH);
        };
        document.addEventListener("mousemove",mv); document.addEventListener("mouseup",up);
      });
    });
  }
  function clamp(v,lo,hi){ return Math.max(lo,Math.min(hi,v)); }

  // ── Dragging Support ──────────────────────────────────────────────────────
  function initDrag(panel) {
    const header = panel.querySelector(".ytai-header");
    if(!header) return;
    
    header.style.cursor = "move"; // Indicate grabbable area
    
    header.addEventListener("mousedown", e => {
      if(["BUTTON", "SVG", "PATH", "INPUT"].includes(e.target.tagName)) return;
      e.preventDefault();
      
      const sX = e.clientX, sY = e.clientY;
      const r = panel.getBoundingClientRect();
      const pW = panel.offsetWidth, pH = panel.offsetHeight;
      const bW = window.innerWidth, bH = window.innerHeight;
      
      const offX = sX - r.left;
      const offY = sY - r.top;
      
      panel.style.bottom = "auto";
      panel.style.right = "auto";
      panel.style.left = r.left + "px";
      panel.style.top = r.top + "px";
      panel.style.margin = "0";

      document.body.style.userSelect = "none";
      panel.style.transition = "none";

      const mv = me => {
        let nx = me.clientX - offX;
        let ny = me.clientY - offY;
        nx = Math.max(0, Math.min(bW - pW, nx));
        ny = Math.max(0, Math.min(bH - pH, ny));
        panel.style.left = nx + "px";
        panel.style.top = ny + "px";
      };

      const up = () => {
        document.removeEventListener("mousemove", mv);
        document.removeEventListener("mouseup", up);
        document.body.style.userSelect = "";
        panel.style.transition = "";
        sp("ytai_left", panel.style.left);
        sp("ytai_top", panel.style.top);
      };

      document.addEventListener("mousemove", mv);
      document.addEventListener("mouseup", up);
    });
    
    const savedLeft = localStorage.getItem("ytai_left");
    const savedTop = localStorage.getItem("ytai_top");
    if(savedLeft && savedTop) {
      panel.style.bottom = "auto";
      panel.style.right = "auto";
      panel.style.margin = "0";
      
      const bW = window.innerWidth, bH = window.innerHeight;
      let leftPx = parseInt(savedLeft) || 0;
      let topPx = parseInt(savedTop) || 0;
      
      leftPx = Math.max(0, Math.min(bW - panel.offsetWidth, leftPx));
      topPx = Math.max(0, Math.min(bH - panel.offsetHeight, topPx));
      
      panel.style.left = leftPx + "px";
      panel.style.top = topPx + "px";
    }
  }

  // ── Markdown ──────────────────────────────────────────────────────────────
  function mdToHtml(raw){
    let t=raw, blocks=[];
    t=t.replace(/```(\w*)\n?([\s\S]*?)```/g,(_,l,c)=>{blocks.push({lang:l||"code",code:c.trimEnd()});return`%%CB${blocks.length-1}%%`;});
    t=t.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
    t=t.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/__(.+?)__/g,"<strong>$1</strong>").replace(/\*(.+?)\*/g,"<em>$1</em>").replace(/`([^`]+)`/g,"<code>$1</code>");
    t=t.replace(/^#### (.+)$/gm,"<h4>$1</h4>").replace(/^### (.+)$/gm,"<h4>$1</h4>").replace(/^## (.+)$/gm,"<h3>$1</h3>").replace(/^# (.+)$/gm,"<h2>$1</h2>");
    t=t.replace(/^(\d+)\. (.+)$/gm,"<li>$2</li>").replace(/^[-*•] (.+)$/gm,"<li>$1</li>");
    t=t.replace(/((?:<li>.*?<\/li>\n?)+)/g,"<ul>$1</ul>");
    t=t.replace(/\n\n+/g,"</p><p>").replace(/\n/g,"<br>");
    t=t.replace(/<p><\/p>/g,"").replace(/<br>\s*<ul>/g,"<ul>").replace(/<\/ul>\s*<br>/g,"</ul>").replace(/<br>\s*<h/g,"<h");
    t=t.replace(/%%CB(\d+)%%/g,(_,i)=>{const{lang,code}=blocks[+i];const ec=code.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");return`<div class="ytai-code-header"><span class="ytai-code-lang">${escHtml(lang)}</span><button class="ytai-copy-btn">📋 Copy</button></div><pre><code class="language-${lang}">${ec}</code></pre>`;});
    return t;
  }

  // ── Utils ─────────────────────────────────────────────────────────────────
  function escHtml(t){ return String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }
  function escAttr(t){ return String(t).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }
  function copyClip(text,btn,def="📋 Copy",suc="✓ Copied!"){
    navigator.clipboard.writeText(text).then(()=>{btn.textContent=suc;btn.classList.add("copied");setTimeout(()=>{btn.textContent=def;btn.classList.remove("copied");},2000);}).catch(()=>{
      const ta=document.createElement("textarea");ta.value=text;ta.style.cssText="position:fixed;left:-9999px";document.body.appendChild(ta);ta.select();document.execCommand("copy");document.body.removeChild(ta);
      btn.textContent=suc;btn.classList.add("copied");setTimeout(()=>{btn.textContent=def;btn.classList.remove("copied");},2000);
    });
  }
  function qs(sel){ return document.querySelector(sel); }
  function sleep(ms){ return new Promise(r=>setTimeout(r,ms)); }

  // ── Icons ─────────────────────────────────────────────────────────────────
  function svgSparkle(s=20){return`<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none"><path d="M12 2L14.5 9.5L22 12L14.5 14.5L12 22L9.5 14.5L2 12L9.5 9.5L12 2Z" fill="currentColor" opacity=".9"/><path d="M19 2L20 5L23 6L20 7L19 10L18 7L15 6L18 5L19 2Z" fill="currentColor" opacity=".6"/></svg>`;}
  function svgX(){return`<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>`;}
  function svgTrash(){return`<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14H6L5 6"/><path d="M9 6V4h6v2"/></svg>`;}
  function svgFilm(){return`<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><rect x="2" y="2" width="20" height="20" rx="2"/><line x1="7" y1="2" x2="7" y2="22"/><line x1="17" y1="2" x2="17" y2="22"/><line x1="2" y1="12" x2="22" y2="12"/></svg>`;}
  function svgSend(){return`<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>`;}
})();
